<option value="'Cabin', sans-serif">Cabin (Normal 400)</option>
<option value="'Archivo Narrow', sans-serif" selected="selected">Archivo Narrow (Normal 400)</option>
<option value="'Play', sans-serif">Play (Normal 400)</option>
<option value="'Pacifico', cursive">Pacifico (Normal 400)</option>
<option value="'Roboto Condensed', sans-serif">Roboto Condensed (Normal 400)</option>
<option value="'Montserrat', sans-serif">Montserrat (Normal 400)</option>
<option value="'Noto Sans', sans-serif">Noto Sans (Normal 400)</option>
<option value="'Lobster', cursive">Lobster (Normal 400)</option>
<option value="'Fjalla One', sans-serif">Fjalla One (Normal 400)</option>
<option value="'Josefin Sans', sans-serif">Josefin Sans (Normal 400)</option>
<option value="'Signika', sans-serif">Signika (Normal 400)</option>
<option value="'Ubuntu Condensed', sans-serif">Ubuntu Condensed (Normal 400)</option>
<option value="'Maven Pro', sans-serif">Maven Pro (Normal 400)</option>
<option value="'Exo 2', sans-serif">Exo 2 (Normal 400)</option>
<option value="'Karla', sans-serif">Karla (Normal 400)</option>
<option value="'Exo', sans-serif">Exo (Normal 400)</option>
<option value="'Dancing Script', cursive">Dancing Script (Normal 400)</option>
<option value="'Righteous', cursive">Righteous (Normal 400)</option>
<option value="'Chewy', cursive">Chewy (Normal 400)</option>
<option value="'Courgette', cursive">Courgette (Normal 400)</option>